name = "findash"
main = "worker/index.ts"
compatibility_date = "2026-05-16"

[build]
command = "npm run build"

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"
